experiment:
  dataset: epinions
  data_config:
    strategy: dataset
    dataset_path: ../data/epinions/processed/filtered_ratings.tsv
    side_information:
    #  prefiltering:
    #    strategy: user_average # Not applied in the paper experiments
  splitting:
    save_on_disk: True
    save_folder: ../data/epinions/splitting/
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
    #validation_splitting:
    # strategy: random_subsampling
    # test_ratio: 0.2
  top_k: 10
  evaluation:
    cutoffs: [10, 5]
    simple_metrics: [nDCG, Precision, Recall, Gini, SEntropy, UserCoverage, ItemCoverage]
    paired_ttest: True
    wilcoxon_test: True
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.GraphRec:
      meta:
        verbose: True
        save_recs: True
        validation_metric: nDCG@10
      epochs: 10
      batch_size: 128
      lr: 0.001
      factors: 64
      social_connections_filepath: ./data/epinions/processed/filtered_social_connections.tsv
      seed: 42
#    Random:
#      meta:
#        verbose: True
#        save_recs: False
#      seed: 42
#    external.MostPop:
#      meta:
#        verbose: True
#        save_recs: True
#    ItemKNN:
#      meta:
#        verbose: True
#        save_recs: True
#      neighbors: 60
#      similarity: cosine
#      implementation: standard